[tox]
minversion = 3.12.0
envlist = python312, units, regression, linting, bandit, build-dart-game-counter

[testenv:units]
install_command = python -m pip install {opts} {packages} --no-compile
download = true
#setenv =
#deps =
commands =
    pytest -v --cov=dart_game_counter --color=yes --cov-report=markdown:cov.md

[testenv:regression]
install_command = pytnon -m pip install {opts} {packages} --no-compile
download = true
#setenv =
#   USERNAME = fRANCIS
deps =
    .[dev]
commands = 
    pytest {env:TEST_DIR} -v --cov=dart_game_counter --color=yes
    
[testenv:linting]
download = true
basepython = python3.12
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[testenv:bandit]
download = true
basepython = python3.12
skip_install = true
deps = bandit>=1.7
commands = bandit -r src\dart...

[testenv:build-dart-game-counter]
basepython = python3.12
skisdist = true
skip_install = true
allowlist_externals =
    pyinstaller
    basepython
    mv
    rmdir
deps = .
commands =
    python -c "from shutil import rmtree; rmtree('build', True); rmtree('dist', True)"
    pyinstaller dart-game-counter.spec
    bash -c "mv dist\dart-game-counter.exe\_internal dist\dart-game-counter   ; \
    cd dist\dart-game-counter-$VERSION-portable-win-x86-64; \
    zip -r ..\dart-game-counter-$VERSION-portable-win-x86-64.zip .;"