[tox]
minversion = 3.12.0
envlist = python312, units, regression, linting, bandit, build-dart-game-counter

[testenv:units]
install_command = python -m pip install {opts} {packages} --no-compile
download = true
#setenv =
#deps =
commands =
    pytest -v --cov=dart_game_counter --color=yes --cov-report=markdown:cov.md

[testenv:regression]
install_command = pytnon -m pip install {opts} {packages} --no-compile
download = true
#setenv =
#   USERNAME = fRANCIS
deps =
    .[dev]
commands = 
    pytest {env:TEST_DIR} -v --cov=dart_game_counter --color=yes
    
[testenv:linting]
download = true
basepython = python3.12
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[testenv:bandit]
download = true
basepython = python3.12
skip_install = true
deps = bandit>=1.7
commands = bandit -r src\dart...

[testenv:build]
basepython = python3.12
deps = pyinstaller

skip_install = false  # install your package so imports work

commands_pre =
    # Install ONLY your package (no dev extras)
    python -m pip install .

commands =
    # Clean previous builds
    python -c "from shutil import rmtree; rmtree('build', True); rmtree('dist', True)"
    python -c "import dart_game_counter as m, subprocess, shutil, os; \
    v=m.__version__; \
    dist_path = f'dist/dart-game-counter-{v}-portable-win-x86-64'; \
    icon_path = 'data/images/dart_icon.ico'; \
    subprocess.run([ \
        'pyinstaller', \
        '--onedir', \
        '--name', f'dart-game-counter-{v}-portable-win-x86-64', \
        '--paths=src', \
        '--add-data', 'data/images;data/images', \
        f'--icon={icon_path}', \
        'src/dart_game_counter/cli.py' \
    ], check=True); \
    shutil.copytree('data', os.path.join(dist_path, 'data'), dirs_exist_ok=True); \
    shutil.make_archive(f'dist/dart-game-counter-{v}-portable-win-x86-64', 'zip', f'dist/dart-game-counter-{v}-portable-win-x86-64')"
